In [1]:
import pandas as pd
import nltk
import string

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [2]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\10mih\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\10mih\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\10mih\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
df = pd.read_csv("Phones_Dataset.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Phones_Dataset.csv'

In [ ]:
df.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price [LKR],Launched Year,Colour,Network,Stock Status,Warranty
0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"LKR 268,504",2024,White,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty
1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"LKR 285,306",2024,Midnight,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty
2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"LKR 302,109",2024,Black,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty
3,Apple,iPhone 16 Plus 128GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"LKR 302,109",2024,Starlight,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty
4,Apple,iPhone 16 Plus 256GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"LKR 318,911",2024,Blue,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty

In [ ]:
df.columns

Index(['Company Name', 'Model Name', 'Mobile Weight', 'RAM', 'Front Camera',
       'Back Camera', 'Processor', 'Battery Capacity', 'Screen Size',
       'Price [LKR]', 'Launched Year', 'Colour', 'Network', 'Stock Status',
       'Warranty'],
      dtype='str')

In [ ]:
df["text"] = (
    df["Company Name"].astype(str) + " " +
    df["Model Name"].astype(str) + " " +
    df["Warranty"].astype(str) + " " +
    df["Stock Status"].astype(str)
)

In [ ]:
df["text"].head()

0    Apple iPhone 16 128GB 1 Year Limited Warranty ...
1    Apple iPhone 16 256GB 1 Year Limited Warranty ...
2    Apple iPhone 16 512GB 1 Year Limited Warranty ...
3    Apple iPhone 16 Plus 128GB 1 Year Limited Warr...
4    Apple iPhone 16 Plus 256GB 1 Year Limited Warr...
Name: text, dtype: str

In [ ]:
stop_words = set(stopwords.words("english"))

lemmatizer = WordNetLemmatizer()

In [ ]:
def preprocess_text(text):

    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Tokenization
    tokens = word_tokenize(text)

    # Remove stop words
    tokens = [word for word in tokens if word not in stop_words]

    # Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    # Join back into a sentence
    return " ".join(tokens)

In [ ]:
sentence = "How much is the Apple iPhone 16?"

print(preprocess_text(sentence))

much apple iphone 16

In [ ]:
df["processed_text"] = df["text"].apply(preprocess_text)

In [ ]:
df[["text", "processed_text"]].head()

,text,processed_text
0,Apple iPhone 16 128GB 1 Year Limited Warranty ...,apple iphone 16 128gb 1 year limited warranty ...
1,Apple iPhone 16 256GB 1 Year Limited Warranty ...,apple iphone 16 256gb 1 year limited warranty ...
2,Apple iPhone 16 512GB 1 Year Limited Warranty ...,apple iphone 16 512gb 1 year limited warranty ...
3,Apple iPhone 16 Plus 128GB 1 Year Limited Warr...,apple iphone 16 plus 128gb 1 year limited warr...
4,Apple iPhone 16 Plus 256GB 1 Year Limited Warr...,apple iphone 16 plus 256gb 1 year limited warr...

In [ ]:
df.to_csv("Phones_Dataset.csv", index=False)

In [1]:
import pandas as pd
import nltk
import string

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [2]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\10mih\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\10mih\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\10mih\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\10mih\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
intents = pd.read_csv("mobixa_intents.csv")

In [4]:
intents.head()

                         text        intent                    response
0             Catch you later       goodbye       Response for goodbye.
1                          Hi      greeting      Response for greeting.
2                Good morning      greeting      Response for greeting.
3       Cost of Redmi Note 14   price_query   Response for price_query.
4  Availability of Galaxy S24  availability  Response for availability.

In [5]:
print(intents.columns)

Index(['text', 'intent', 'response'], dtype='str')

In [6]:
intents["lowercase"] = intents["text"].str.lower()

In [7]:
intents[["text", "lowercase"]].head()

                         text                   lowercase
0             Catch you later             catch you later
1                          Hi                          hi
2                Good morning                good morning
3       Cost of Redmi Note 14       cost of redmi note 14
4  Availability of Galaxy S24  availability of galaxy s24

In [8]:
intents["no_punctuation"] = intents["lowercase"].apply(
    lambda x: x.translate(str.maketrans('', '', string.punctuation))
)

In [9]:
intents[["lowercase", "no_punctuation"]].head()

                    lowercase              no_punctuation
0             catch you later             catch you later
1                          hi                          hi
2                good morning                good morning
3       cost of redmi note 14       cost of redmi note 14
4  availability of galaxy s24  availability of galaxy s24

In [10]:
intents["tokens"] = intents["no_punctuation"].apply(word_tokenize)
intents[["no_punctuation", "tokens"]].head()

               no_punctuation                           tokens
0             catch you later              [catch, you, later]
1                          hi                             [hi]
2                good morning                  [good, morning]
3       cost of redmi note 14      [cost, of, redmi, note, 14]
4  availability of galaxy s24  [availability, of, galaxy, s24]

In [11]:
stop_words = set(stopwords.words("english"))

intents["no_stopwords"] = intents["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

In [12]:
intents[["tokens", "no_stopwords"]].head()

                            tokens                 no_stopwords
0              [catch, you, later]               [catch, later]
1                             [hi]                         [hi]
2                  [good, morning]              [good, morning]
3      [cost, of, redmi, note, 14]      [cost, redmi, note, 14]
4  [availability, of, galaxy, s24]  [availability, galaxy, s24]

In [13]:
stemmer = PorterStemmer()

intents["stemmed"] = intents["no_stopwords"].apply(
    lambda words: [stemmer.stem(word) for word in words]
)
intents[["no_stopwords", "stemmed"]].head()

                  no_stopwords                  stemmed
0               [catch, later]           [catch, later]
1                         [hi]                     [hi]
2              [good, morning]             [good, morn]
3      [cost, redmi, note, 14]  [cost, redmi, note, 14]
4  [availability, galaxy, s24]     [avail, galaxi, s24]

In [14]:
lemmatizer = WordNetLemmatizer()

intents["lemmatized"] = intents["no_stopwords"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

In [15]:
intents[["no_stopwords", "lemmatized"]].head()

                  no_stopwords                   lemmatized
0               [catch, later]               [catch, later]
1                         [hi]                         [hi]
2              [good, morning]              [good, morning]
3      [cost, redmi, note, 14]      [cost, redmi, note, 14]
4  [availability, galaxy, s24]  [availability, galaxy, s24]

In [16]:
intents["processed_text"] = intents["lemmatized"].apply(
    lambda words: " ".join(words)
)
intents[["text", "processed_text"]].head()

                         text           processed_text
0             Catch you later              catch later
1                          Hi                       hi
2                Good morning             good morning
3       Cost of Redmi Note 14       cost redmi note 14
4  Availability of Galaxy S24  availability galaxy s24

In [17]:
intents.to_csv("mobixa_intents_clean.csv", index=False)

In [18]:
import pandas as pd

accessories = pd.read_csv("mobile_accessories.csv")

# View the first 5 rows
accessories.head()

,accessory_name,category,brand,compatible_with,price_lkr,stock,warranty,color
0,Apple 20W USB-C Power Adapter,Charger,Apple,iPhone,8990,25,12 Months,White
1,Apple MagSafe Charger,Wireless Charger,Apple,iPhone 12 and later,15990,18,12 Months,White
2,Samsung 25W Super Fast Charger,Charger,Samsung,Galaxy Series,7990,30,12 Months,Black
3,Samsung 45W Super Fast Charger,Charger,Samsung,Galaxy Series,12990,20,12 Months,Black
4,Anker Nano 30W Charger,Charger,Anker,Universal,10990,40,18 Months,White

In [19]:
print(accessories.columns)

Index(['accessory_name', 'category', 'brand', 'compatible_with', 'price_lkr',
       'stock', 'warranty', 'color'],
      dtype='str')

In [20]:
import nltk
import string

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [23]:
print(accessories.columns)

Index(['accessory_name', 'category', 'brand', 'compatible_with', 'price_lkr',
       'stock', 'warranty', 'color'],
      dtype='str')

In [26]:
# Convert to lowercase
accessories["lowercase"] = accessories["accessory_name"].str.lower()

In [27]:
# Remove punctuation
accessories["no_punctuation"] = accessories["lowercase"].apply(
    lambda x: x.translate(str.maketrans('', '', string.punctuation))
)

In [28]:
# Tokenization
accessories["tokens"] = accessories["no_punctuation"].apply(word_tokenize)

In [29]:
# Remove stop words
stop_words = set(stopwords.words("english"))

accessories["no_stopwords"] = accessories["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

In [30]:
# Stemming
stemmer = PorterStemmer()

accessories["stemmed"] = accessories["no_stopwords"].apply(
    lambda words: [stemmer.stem(word) for word in words]
)

In [31]:
# Lemmatization
lemmatizer = WordNetLemmatizer()

accessories["lemmatized"] = accessories["no_stopwords"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

In [32]:
# Final processed text
accessories["processed_text"] = accessories["lemmatized"].apply(
    lambda words: " ".join(words)
)

In [33]:
# Save the cleaned dataset
accessories.to_csv("mobile_accessories_clean.csv", index=False)

In [ ]:
# Display results
print(accessories[["accessory_name", "processed_text"]].head())

                   accessory_name                  processed_text
0   Apple 20W USB-C Power Adapter    apple 20w usbc power adapter
1           Apple MagSafe Charger           apple magsafe charger
2  Samsung 25W Super Fast Charger  samsung 25w super fast charger
3  Samsung 45W Super Fast Charger  samsung 45w super fast charger
4          Anker Nano 30W Charger          anker nano 30w charger

In [35]:
faq = pd.read_csv("mobixa_faq.csv")

In [36]:
print(faq.columns)

Index(['question', 'answer', 'category'], dtype='str')

In [37]:
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Load dataset
faq = pd.read_csv("mobixa_faq.csv")

# Convert to lowercase
faq["lowercase"] = faq["question"].str.lower()

# Remove punctuation
faq["no_punctuation"] = faq["lowercase"].apply(
    lambda x: x.translate(str.maketrans('', '', string.punctuation))
)

# Tokenization
faq["tokens"] = faq["no_punctuation"].apply(word_tokenize)

# Remove stop words
stop_words = set(stopwords.words("english"))

faq["no_stopwords"] = faq["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

# Stemming
stemmer = PorterStemmer()

faq["stemmed"] = faq["no_stopwords"].apply(
    lambda words: [stemmer.stem(word) for word in words]
)

# Lemmatization
lemmatizer = WordNetLemmatizer()

faq["lemmatized"] = faq["no_stopwords"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

# Final processed text
faq["processed_text"] = faq["lemmatized"].apply(
    lambda words: " ".join(words)
)

# Save cleaned dataset
faq.to_csv("mobixa_faq_clean.csv", index=False)

# View results
print(faq[["question", "processed_text"]].head())

                                   question                    processed_text
0    Is accidental damage covered in Kandy?   accidental damage covered kandy
1        What are your opening hours today?                opening hour today
2            Can I track my order in Kandy?                 track order kandy
3  Do you offer islandwide delivery please.  offer islandwide delivery please
4   Do phones have a warranty this weekend?            phone warranty weekend

In [38]:
repair = pd.read_csv("repair_services.csv")
print(repair.columns)

Index(['repair_service', 'supported_brand', 'estimated_price_lkr',
       'estimated_time', 'warranty', 'description'],
      dtype='str')

In [39]:
import pandas as pd
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [40]:
# Load dataset
repair = pd.read_csv("repair_services.csv")

In [41]:
# Convert to lowercase
repair["lowercase"] = repair["repair_service"].str.lower()

In [42]:
# Remove punctuation
repair["no_punctuation"] = repair["lowercase"].apply(
    lambda x: x.translate(str.maketrans('', '', string.punctuation))
)

In [43]:
# Tokenization
repair["tokens"] = repair["no_punctuation"].apply(word_tokenize)

In [44]:
# Remove stop words
stop_words = set(stopwords.words("english"))

In [45]:
repair["no_stopwords"] = repair["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

In [46]:
# Stemming
stemmer = PorterStemmer()

repair["stemmed"] = repair["no_stopwords"].apply(
    lambda words: [stemmer.stem(word) for word in words]
)

In [47]:
# Lemmatization
lemmatizer = WordNetLemmatizer()

repair["lemmatized"] = repair["no_stopwords"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

In [48]:
# Final processed text
repair["processed_text"] = repair["lemmatized"].apply(
    lambda words: " ".join(words)
)

In [49]:
# Save cleaned dataset
repair.to_csv("repair_services_clean.csv", index=False)

In [50]:
# Display results
print(repair[["repair_service", "processed_text"]].head())

        repair_service       processed_text
0   Screen Replacement   screen replacement
1   Screen Replacement   screen replacement
2   Screen Replacement   screen replacement
3  Battery Replacement  battery replacement
4  Battery Replacement  battery replacement