# Notebook 02 - Data Preprocessing

This notebook performs data cleaning for all Mobixa chatbot datasets.

Datasets:
- Product Dataset
- Mobile Accessories
- Repair Services
- FAQ
- Intent Dataset
- NER Dataset

In [ ]:
import pandas as pd
import numpy as np
import re
import string

import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jayas\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jayas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\jayas\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
products = pd.read_csv("../dataset/Product Dataset.csv")

accessories = pd.read_csv("../dataset/mobile_accessories.csv")

repairs = pd.read_csv("../dataset/repair_services.csv")

faq = pd.read_csv("../dataset/mobixa_faq.csv")

intents = pd.read_csv("../dataset/mobixa_intents.csv")

entities = pd.read_csv("../dataset/entities.csv")

In [ ]:
stop_words = set(stopwords.words("english"))

lemmatizer = WordNetLemmatizer()

In [ ]:
def remove_spaces(df):

    return df.apply(
        lambda col: col.str.strip()
        if col.dtype=="object"
        else col
    )


def lowercase(df):

    return df.apply(
        lambda col: col.str.lower()
        if col.dtype=="object"
        else col
    )

In [ ]:
def clean_text(text):

    text = text.lower()

    text = re.sub(r"http\S+|www\S+","",text)

    text = text.translate(
        str.maketrans("","",string.punctuation)
    )

    words = word_tokenize(text)

    words = [
        word for word in words
        if word not in stop_words
    ]

    words = [
        lemmatizer.lemmatize(word)
        for word in words
    ]

    return " ".join(words)

In [ ]:
products.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price [LKR],Launched Year,Colour,Network,Stock Status,Warranty
0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"LKR 268,504",2024,White,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty
1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"LKR 285,306",2024,Midnight,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty
2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"LKR 302,109",2024,Black,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty
3,Apple,iPhone 16 Plus 128GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"LKR 302,109",2024,Starlight,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty
4,Apple,iPhone 16 Plus 256GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"LKR 318,911",2024,Blue,"5G, 4G, 3G, 2G",In Stock,1 Year Limited Warranty

In [ ]:
products.isnull().sum()

Company Name        0
Model Name          0
Mobile Weight       0
RAM                 0
Front Camera        0
Back Camera         0
Processor           0
Battery Capacity    0
Screen Size         0
Price [LKR]         0
Launched Year       0
Colour              0
Network             0
Stock Status        0
Warranty            0
dtype: int64

In [ ]:
products = products.dropna()

In [ ]:
products = products.drop_duplicates()

In [ ]:
products = remove_spaces(products)

In [ ]:
products = lowercase(products)

In [ ]:
products.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price [LKR],Launched Year,Colour,Network,Stock Status,Warranty
0,apple,iphone 16 128gb,174g,6gb,12mp,48mp,a17 bionic,"3,600mah",6.1 inches,"lkr 268,504",2024,white,"5g, 4g, 3g, 2g",in stock,1 year limited warranty
1,apple,iphone 16 256gb,174g,6gb,12mp,48mp,a17 bionic,"3,600mah",6.1 inches,"lkr 285,306",2024,midnight,"5g, 4g, 3g, 2g",in stock,1 year limited warranty
2,apple,iphone 16 512gb,174g,6gb,12mp,48mp,a17 bionic,"3,600mah",6.1 inches,"lkr 302,109",2024,black,"5g, 4g, 3g, 2g",in stock,1 year limited warranty
3,apple,iphone 16 plus 128gb,203g,6gb,12mp,48mp,a17 bionic,"4,200mah",6.7 inches,"lkr 302,109",2024,starlight,"5g, 4g, 3g, 2g",in stock,1 year limited warranty
4,apple,iphone 16 plus 256gb,203g,6gb,12mp,48mp,a17 bionic,"4,200mah",6.7 inches,"lkr 318,911",2024,blue,"5g, 4g, 3g, 2g",in stock,1 year limited warranty

In [ ]:
products.to_csv("../dataset/products_clean.csv",index=False)

In [ ]:
accessories.head()

,accessory_name,category,brand,compatible_with,price_lkr,stock,warranty,color
0,Apple 20W USB-C Power Adapter,Charger,Apple,iPhone,8990,25,12 Months,White
1,Apple MagSafe Charger,Wireless Charger,Apple,iPhone 12 and later,15990,18,12 Months,White
2,Samsung 25W Super Fast Charger,Charger,Samsung,Galaxy Series,7990,30,12 Months,Black
3,Samsung 45W Super Fast Charger,Charger,Samsung,Galaxy Series,12990,20,12 Months,Black
4,Anker Nano 30W Charger,Charger,Anker,Universal,10990,40,18 Months,White

In [ ]:
accessories.isnull().sum()

accessory_name     0
category           0
brand              0
compatible_with    0
price_lkr          0
stock              0
warranty           0
color              0
dtype: int64

In [ ]:
accessories = accessories.dropna()

In [ ]:
accessories = accessories.drop_duplicates()

In [ ]:
accessories = remove_spaces(accessories)

In [ ]:
accessories = lowercase(accessories)

In [ ]:
accessories.head()

,accessory_name,category,brand,compatible_with,price_lkr,stock,warranty,color
0,apple 20w usb-c power adapter,charger,apple,iphone,8990,25,12 months,white
1,apple magsafe charger,wireless charger,apple,iphone 12 and later,15990,18,12 months,white
2,samsung 25w super fast charger,charger,samsung,galaxy series,7990,30,12 months,black
3,samsung 45w super fast charger,charger,samsung,galaxy series,12990,20,12 months,black
4,anker nano 30w charger,charger,anker,universal,10990,40,18 months,white

In [ ]:
accessories.to_csv("../dataset/accessories_clean.csv",index=False)

In [ ]:
repairs.head()

,repair_service,supported_brand,estimated_price_lkr,estimated_time,warranty,description
0,Screen Replacement,Apple,35000,2 Hours,3 Months,Original-quality screen replacement
1,Screen Replacement,Samsung,28000,2 Hours,3 Months,Genuine display replacement
2,Screen Replacement,Xiaomi,18000,2 Hours,3 Months,High-quality replacement display
3,Battery Replacement,Apple,18000,1 Hour,6 Months,Original battery replacement
4,Battery Replacement,Samsung,12000,1 Hour,6 Months,Genuine Samsung battery

In [ ]:
repairs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   repair_service       30 non-null     object
 1   supported_brand      30 non-null     object
 2   estimated_price_lkr  30 non-null     int64
 3   estimated_time       30 non-null     object
 4   warranty             30 non-null     object
 5   description          30 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.5+ KB

In [ ]:
repairs.isnull().sum()

repair_service         0
supported_brand        0
estimated_price_lkr    0
estimated_time         0
warranty               0
description            0
dtype: int64

In [ ]:
repairs = repairs.dropna()

In [ ]:
repairs.duplicated().sum()

np.int64(0)

In [ ]:
repairs = repairs.drop_duplicates()

In [ ]:
repairs = repairs.apply(
    lambda col: col.str.strip() if col.dtype == "object" else col
)

In [ ]:
repairs = repairs.apply(
    lambda col: col.str.lower() if col.dtype == "object" else col
)

In [ ]:
repairs.head()

,repair_service,supported_brand,estimated_price_lkr,estimated_time,warranty,description
0,screen replacement,apple,35000,2 hours,3 months,original-quality screen replacement
1,screen replacement,samsung,28000,2 hours,3 months,genuine display replacement
2,screen replacement,xiaomi,18000,2 hours,3 months,high-quality replacement display
3,battery replacement,apple,18000,1 hour,6 months,original battery replacement
4,battery replacement,samsung,12000,1 hour,6 months,genuine samsung battery

In [ ]:
repairs.to_csv("../dataset/repair_services_clean.csv", index=False)

In [ ]:
faq.head()

,question,answer,category
0,Is accidental damage covered in Kandy?,"No, accidental damage is not covered.",Warranty
1,What are your opening hours today?,We are open daily from 9:00 AM to 8:00 PM.,Store
2,Can I track my order in Kandy?,"Yes, we'll provide a tracking update.",Delivery
3,Do you offer islandwide delivery please.,"Yes, we deliver across Sri Lanka.",Delivery
4,Do phones have a warranty this weekend?,"Yes, all eligible phones include a warranty.",Warranty

In [ ]:
faq = faq.dropna()
faq = faq.drop_duplicates()
faq = remove_spaces(faq)
faq = lowercase(faq)

In [ ]:
faq["question"] = faq["question"].apply(clean_text)

In [ ]:
faq.to_csv("../dataset/faq_clean.csv",index=False)

In [ ]:
intents.head()

                         text        intent                    response
0             Catch you later       goodbye       Response for goodbye.
1                          Hi      greeting      Response for greeting.
2                Good morning      greeting      Response for greeting.
3       Cost of Redmi Note 14   price_query   Response for price_query.
4  Availability of Galaxy S24  availability  Response for availability.

In [ ]:
intents["text"] = intents["text"].apply(clean_text)

In [ ]:
intents.head()

                      text        intent                    response
0              catch later       goodbye       Response for goodbye.
1                       hi      greeting      Response for greeting.
2             good morning      greeting      Response for greeting.
3       cost redmi note 14   price_query   Response for price_query.
4  availability galaxy s24  availability  Response for availability.

In [ ]:
intents.to_csv("../dataset/intents_clean.csv",index=False)

In [ ]:
entities.head()

  entity_type entity_value                            synonyms
0       brand        Apple                  apple, iphone, ios
1       brand      Samsung        samsung, galaxy, note, ultra
2       brand       Xiaomi             xiaomi, redmi, poco, mi
3       brand         Oppo                oppo, reno, a series
4       brand         Vivo  vivo, y series, v series, x series

In [ ]:
entities = entities.dropna()
entities = entities.drop_duplicates()
entities = remove_spaces(entities)

In [ ]:
entities.head()

  entity_type entity_value                            synonyms
0       brand        Apple                  apple, iphone, ios
1       brand      Samsung        samsung, galaxy, note, ultra
2       brand       Xiaomi             xiaomi, redmi, poco, mi
3       brand         Oppo                oppo, reno, a series
4       brand         Vivo  vivo, y series, v series, x series

In [ ]:
entities.to_csv("../dataset/entities_clean.csv",index=False)

In [ ]:
print("All datasets have been cleaned successfully!")

All datasets have been cleaned successfully!